// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// import { AntdRegistry } from "@ant-design/nextjs-registry";
// import "antd/dist/reset.css";
import { ReduxProvider } from "../redux/provider";
import { Poppins, Epilogue, Rubik, Suranna, Jost, Inter } from "next/font/google";
import localFont from "@next/font/local";
import NextTopLoader from "nextjs-toploader";
import {getServerSession} from "next-auth/next";
import {authOptions} from "@/app/auth";
import MainLayout from "@/components/common/Mainlayout"
import Script from "next/script";
// import { ConfigProvider } from "antd";
// import MainLayout from "@/components/MainLayout";
import "@/app/globals.css";


const suranna = Suranna({
  subsets: [],
  weight: ["400"], // You can also use other available weights
  variable: "--font-suranna",
});

const inter = Inter({
  subsets: [],
  weight: ["400", "500", "600", "700"], // You can also use other available weights
  variable: "--font-inter",
});

const jost = Jost({
  subsets: [],
  weight: ["400", "500", "600", "700"], // You can also use other available weights
  variable: "--font-jost",
});

const suse = localFont({
  src: "../../public/font/SUSE/SUSE-VariableFont_wght.ttf",
  //  weight: ["400", "500", "600", "700"] ,
  variable: "--font-suse",
});

const qasira = localFont({
  src: "../../public/font/Qasira.otf",
  //  weight: ["400", "500", "600", "700"] ,
  variable: "--font-Qasira",
});

const bentonsans_comp_medium = localFont({
  src: "../../public/font/bentonsans-comp-medium.otf",
  //  weight: ["400", "500", "600", "700"] ,
  variable: "--font-bentonsans_comp_medium",
});

const bentonSans_bold = localFont({
  src: "../../public/font/BentonSans-Bold.otf",
  //  weight: ["400", "500", "600", "700"] ,
  variable: "--font-bentonSans_bold",
});

// export const metadata = {
//   title: "Parmartham",
//   icons: {
//     icon: "/favicon.ico",
//   },
// };

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  // const customTheme = {
  //   components: {
  //     Button: {
  //       algorithm: true,
  //       fontFamily: '"Inter", sans-serif',
  //       colorSecondaryBg: "#3F4FE41A",
  //       colorSecondaryBorder: "#3F4FE4",
  //       colorSecondaryText: "#3F4FE4",
  //       colorSecondaryHover: "#3F4FE433",
  //       color: "white",
  //     },
  //     Spin: {
  //       contentHeight: "100%",
  //     },
  //     Steps: {
  //       iconSize: 50,
  //       // titleLineHeight:
  //     },
  //     Pagination: {
  //       /* here is your component tokens */
  //       itemSize: 36,
  //       // itemSizeSM:32,
  //       fontSize: 20,
  //     },
  //   },
  //   token: {
  //     colorPrimary: "#3F4FE4",
  //     fontFamily: '"Inter", sans-serif',
  //   },
  // };

  return (
    <html lang="en">
      <body
        style={{ overflowX: "hidden" }}  
        className={`${inter.variable} ${jost.variable} ${suranna.variable} `}
        // className={`${poppins.variable}`}
      >
        <NextTopLoader />
        <ReduxProvider session={session}>
          <MainLayout>{children}</MainLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
